### PR TITLE
To merge

### PR DESCRIPTION
**Pull request by lukasbystricky**
I see what you mean about undoing your previous changes. OK, this should be cleaner, and I've also removed some unnecessary semantics in the preface.

### CODE REVIEW

**Comment by acabal** [comment]
I don't think we need this... the long description doesn't need further edits (I have reviewed and edited it myself) and we can leave James' preface as-is.

**Comment by lukasbystricky** [comment]
Are you sure? For the preface I was bringing the reference to Book 5 in line with what you'd done in the long description for Book 11; previously I'd had “Book <span ...>V</span>”.

**Comment by acabal** [comment]
If anything we can change the long description to say Book XI. The long description doesn't necessarily have to match what's in the text itself, since we wrote it and not the author. I'll update it to say Book XI.

**Comment by lukasbystricky** [comment]
Ok, there's also quotes around the reference in the preface, I'm not so sure those are needed anymore. For what it's worth originally James called it Book Fifth in the preface, but I thought I should change that to match the actual Book titles we ended up using (I realize now that should have been an editorial commit too).

**Comment by acabal** [comment]
OK, I've removed the quotes there too

**Pull request closed without merging**
